### ISSUE TITLE
Translate eror

### ISSUE THREAD

**Issue by yusufmor** [pystage/pystage#105]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yusuf\AppData\Local\Programs\Python\Python311\Lib\site-packages\pystage\convert\sb3.py", line 448, in <module>
    project = get_intermediate(data, project_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yusuf\AppData\Local\Programs\Python\Python311\Lib\site-packages\pystage\convert\sb3.py", line 234, in get_intermediate
    block = get_block(b, blocks, target["isStage"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yusuf\AppData\Local\Programs\Python\Python311\Lib\site-packages\pystage\convert\sb3.py", line 157, in get_block
    res["next"] = get_block(blocks[block["next"]], blocks, stage)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yusuf\AppData\Local\Programs\Python\Python311\Lib\site-packages\pystage\convert\sb3.py", line 155, in get_block
    res["params"][i] = get_block(blocks[value], blocks, stage)
                                 ~~~~~~^^^^^^^
KeyError: None

**Comment by kaiec** [comment]
This is not enough information to track down the problem. It might already be fixed by the new 0.1.0 release.

If not, please provide the full error log and the SB3 file you used. If it works, you can use the online converter now and send the URL of the conversion: https://convert.pystage.org/

Closing this for now.
