### ISSUE TITLE
I have a porblem with export.

### ISSUE THREAD

**Issue by tymon-k** [pystage/pystage#110]
I have an error:
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\tymon\VNEV\Lib\site-packages\pystage\convert\__init__.py", line 1, in <module>
    from .code_writer import CodeWriter
  File "C:\Users\tymon\VNEV\Lib\site-packages\pystage\convert\code_writer.py", line 11, in <module>
    from pystage.core.sprite import CoreSprite
  File "C:\Users\tymon\VNEV\Lib\site-packages\pystage\core\__init__.py", line 1, in <module>
    from .sprite import CoreSprite
  File "C:\Users\tymon\VNEV\Lib\site-packages\pystage\core\sprite.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Please for help.
Thank you.

**Comment by kaiec** [comment]
`pip install setuptools` should fix this. We seem to miss a dependency on it.
