### ISSUE TITLE
TypeError: rect() takes no keyword arguments

### ISSUE THREAD

**Issue by Askaat** [pystage/pystage#19]
When im trying to start my program, i have an issue with pygames. Here is the error : 

```
New costume: backdrop1 -> C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\site-packages\pystage\images\zombie_idle.png
Traceback (most recent call last):
  File "c:/Users/Me/Documents/script/test/scratch_project.py", line 8, in <module>
    stage.pystage_makevariable('costume')
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\site-packages\pystage\core\_variables.py", line 82, in pystage_makevariable
    monitor = Monitor(self, name)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\site-packages\pystage\core\monitors.py", line 40, in __init__
    self.update_image()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\site-packages\pystage\core\monitors.py", line 62, in update_image
    pygame.draw.rect(rect_surface, self._color, (0,0, rect_w, rect_h), border_radius=3)
TypeError: rect() takes no keyword arguments
```

**Comment by kaiec** [comment]
I found it, your version of PyGame is too old. PyStage requires PyGame 2.0 or higher.
See the PyGame docs:

> Changed in pygame 2.0.0: Added support for keyword arguments.

https://www.pygame.org/docs/ref/draw.html#pygame.draw.rect
