### ISSUE TITLE
Conversion of input to move() block causes stack trace in conversion

### ISSUE THREAD

**Issue by VictorNorman** [pystage/pystage#20]
When converting this Scratch project, https://scratch.mit.edu/projects/44316116/, the resulting json contains this movesteps block:

        "p}:lf]e~+udF{Q1K)Cg2": {
          "opcode": "motion_movesteps",
          "next": "`17EC{dJnXCZk0C/zXO~",
          "parent": "P-^9l8t(g]U4_g+/%;uV",
          "inputs": { "STEPS": [1, [4, 10]] },
          "fields": {},
          "shadow": false,
          "topLevel": false
        },

Conversion produces this error:

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/vtn2/src/pystage/src/pystage/convert/sb3.py", line 449, in <module>
    project = get_intermediate(data, project_name)
  File "/Users/vtn2/src/pystage/src/pystage/convert/sb3.py", line 235, in get_intermediate
    block = get_block(b, blocks, target["isStage"])
  File "/Users/vtn2/src/pystage/src/pystage/convert/sb3.py", line 158, in get_block
    res["next"] = get_block(blocks[block["next"]], blocks, stage)
  File "/Users/vtn2/src/pystage/src/pystage/convert/sb3.py", line 156, in get_block
    res["params"][i] = get_block(blocks[value], blocks, stage)
  File "/Users/vtn2/src/pystage/src/pystage/convert/sb3.py", line 154, in get_block
    res["params"][i] = get_input_value(value, stage)
  File "/Users/vtn2/src/pystage/src/pystage/convert/sb3.py", line 104, in get_input_value
    if value.strip() == '':
AttributeError: 'int' object has no attribute 'strip'
```

This is because the value is 10, not "10", so you cannot strip() an integer. 

When I edited this project, replacing 10 by 10 (yes, just erasing 10 and retyping it), then the resulting json is correct, putting 10 in double quotes as a string...

So, the solution may be to not trust that a value of "type" 4 (number) is represented by a string in the json, and actually test it before calling strip().

**Comment by kaiec** [comment]
Thanks for the solution, @VictorNorman!
