### ISSUE TITLE
Bug when running with Thonny

### ISSUE THREAD

**Issue by litz13** [pystage/pystage#6]
Might also be a problem with PyCharm or other IDEs that run python internally. In this case they seem to mess with the stdout and stderr like we do...

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/__main__.py", line 43, in <module>
    MainCPythonBackend(target_cwd).mainloop()
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 72, in mainloop
    self._handle_normal_command(msg)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 253, in _handle_normal_command
    self.send_message(real_response)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 908, in send_message
    sys.stdout.flush()
ValueError: I/O operation on closed file.

Backend terminated or disconnected. Use 'Stop/Restart' to restart.

**Comment by kaiec** [comment]
PyCharm and Mu are unaffected, so this is indeed specific to Thonny so far. As the redirect of stderr we use might cause the problem, I tend to deactivate it by default, with a function to use the redirect if the output should be hidden. We should also provide the grid background and all other images in png format so that for our own examples, no in game SVG conversion is required.

**Comment by kaiec** [comment]
Thonny also seems to manage to circumvent our environment settings which leads to problems under KDE (We set SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR to 0, see https://www.pygame.org/docs/ref/pygame.html). I love Thonny more and more...

**Comment by kaiec** [comment]
As the redirects produce a lot of problems also elsewhere (not working under Windows and Mac), we can close this, and rather need a better solution for SVG handling.
